---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: install git
    yum: name=git state=present
  - name: build dockerfile
  - name: get the dockerfile from github
    git: repo=https://github.com/prady12091988/EDUPROJECT.git dest=/tmp/gitrepo
    command: chdir=/tmp/gitrepo/ docker build -t deployimage:devopsedu/webapp .
  - name: run the dockerfile
    command: docker run -itd -P deployimage:devopsedu/webapp .
